language: ruby
rvm:
- 2.0.0
env:
  global:
    - secure: "WYUZW4sQn4w3eQsbAdELG1ipfOcGGdeZY9yavdM5LLyHl+YZM8GRONUnH4xhc/fHqA9KSA9LKRTN94c8jKRjafrPomgVlSs5ZuQIzFAbTJPRZLSjzP+JD9/kvFtfX46JBhDc29yY6YGHJvVHILFGDAOx+VwtORl+rPNeyLvC3cI="
    - secure: "OFYyk68PEc2r0pqwe/pTbC0W+jKbVC/g2Hrr8m61P8xFVa1rAyGafR/zeBtpvrAfDFREfNNL4lBTjCtHYBtmgdXD0QvQ5jRUBdkdnq9MacwijJikVDmtfPXsq+KO1FCAo5fk9NuTHAVh2M/+YuDCTjp0bi+KdUT6RX/iYkwchDg="
    - secure: "Sv8dZ3potKpCPVUdyGDB0i04gJKfDeCmNnwjLuySZDNsPtZVb5Lg5JRUMK4kwpKrelNeagxRFHVxN1so+mye4MEfGccHqDdHEh6+yIoODXwxxzcMi4/c6l9i39MPdUXwp4NXZHZC2nIY3EcPGZJOWrgNgI2HGnRPRRxOU5kUIKA="
    - secure: "XMOAyGUvIrdbPqG5rULn6DR2k5zK4zlYobqarOlmqzjwpi2xaOs4hy7l0aEZC5VySFZuco9ipDwUDQudPTPxOzmpyMg0nhv9eIVgm/v/0P2Nf4wj/MMmRLHpoYE+zBV/tkmWc/cKmTVozz6kERbVAZKJeirkm/3Zx8AuRJZlrVw="
    - secure: "gxelA+ffR0UEYC0tjGYfm5Mo7vEL1636nao/axugNm6o/bbqW3+LYXFxbGfcwEkzUKCuNOHFETgJx+EBlEEQgYgbBIGdA83GH5lQSTem3WmXNjM8tuJm1QCwvXRYY3fZWDB99kwMpM6a4+tX62RQ0xXwzn6tMoVbXdqt/wu4SLA="
    - secure: "H+77McpFSyQnhWzie6txSurfCWb/BaVDE1fEXm6IaezRqNylgvndMT4PcsaUiA4n7yGAhQdaEdLu4adFT5vqglC4RGk4pOykSXczrKmKUZwX2EB0D9fwlzZsYFFBvoE2s3Z3IiPYAHc9LEw4y7dC0+3BxlK04rgukK9w8q/oYPQ="
    - secure: "a2mp7i3C5YAdZPA7lwKswPbgRc2DmUFgMDuUCQiS5oqKX1eJYBhYtHI95zJyvSm8ICFAha6X3Wih5CsoE8GFSysPNTO7S1o048fssnyExkY9f7M2CnTz87eo0KEyjyJJDcAbJMgXOfKivKU+g/yDKQ+g+JyieeDfr4wj1s+lSDk="
    - secure: "HVRkwp0LY+li2TOH/CjqlaeiWJwRYMX8naq1Dmz5dFOB82+wdmDaISCuaf71miSa3wpUC+vX8j9wFGtU5y0/xCwjtKKOVC4KgPOPjs/joc4GoeJ/We5TeynhB5L8oa0uhC0u+CAXBnmKX59RfXIhv2GkD5uPcbphpskL+rpKDK4="
    - secure: "fF8pxold/SaoXziNZRPJyu+zXPn1QtbOvuw9yM3SieChhqYsRev1Ggt33fa32h40sLXe1thF0CjzWmzpQmAh+FfcvtDsF4Ic9bHQHnWaqa0oOBhva2Qd5YIoXS10YgfNg8/iCfC0eMhPH8YFr6OzOY9MpMUdrWOT9QzG1JgZ0R4="
    - secure: "GIyXYdDZmaxV9+XFqehMhmmcLDvOJvZx+SxC7+tnL5KylHwgGSqoDf0XwyBE/zglhVfyvOCWRpWm/xI289h3rB00Mbg8VPJ/ramg4YnEdfZeIq0CCx1rTg7+Pj0F4lPeRToQpXbaknmbbiN93HnCIAoaGDYly2ntUVwxHGHrM/4="
    - secure: "cL1VU+RMIsmKpEFeAfqoJHPi0kvzrWtQjc9egh93OIUcKSwfbU1qOYy/ORWvUzuF2EJEJMEUjvWHQrqinwJ0PPdBIJbIsC4ip2UcUSnEZV+CIcNkgA7z8cI0zXSMsbev8lnUbxdnwE+H9Wg0hcxt60k8xgirdvtGdxUzcEJ9nkw="
    - secure: "IW+4m6EmSOOrHtpAg0RTRnwLa8j/Q+qTCtF6AHCcXmxWtE2pMLOzUPmCU4TvuKpmeRQb2ESEbFFFgB1i4w6m+09OMc0LUmxMjg9dGAfmu1kfy+eaIMFoQl6oE8bM4knNbu0O1quR1z0+XmITdrMIVcwjs4ky4JveHPbv1RoCDV4="
    - secure: "Fr9xopOSqMbYtDJrjvNxkfB8ipC9vYxFnB/StVb31VSXY/12Yn1CpTdtY9C69zVYk5t3tfpNxmbsx798pfzEnnHBYwqmaXtM7HVvcmIcRptNJiMSq2s45MG8aU9WF70+xPTxCLkK3SPjAOzEZNV2063KMQsTJ3NSLOhCrrmOAfg="
    - secure: "VFa1np4HLLBTST7RdolMAdWmZGFe7VX31UhImyOmHiH92i18+Ndb6e26BYqYg6nVn/NPDMfBh8+TyDBDgdWhPoW4CcJW13HZUkjgJ5q8mEuxIxO6eA8/e00eXkukC2N9yxQXB/avTmDWFD3LMW7GkI4t0k4m/s64o/Z3fcZn4HA="
    - secure: "XCU70UJ9SHblB4SFq170+8wzuMUXm7AMfIn3mWmmnN58lQcYxNVp7aJOTukmmrfmlbahsalsteQ6GOJ0lwz8dDZOckd49FJYG5jlJP0swu/Ye/LyUs5n8kW6wjK6c2b3dPAa1Wz+tbikGZ/86xQzbiixMtnG52CGbKiwN++DF88="
    - secure: "aaumynGVEhjjfBAj7/MH9RzRpDJ22kqYPtToBDjVLV1HUIdDVoFGpm+VO4JLWmSuTjqQyX3yNKCgTR/xWiPHgP1HOZPjzmoCT7PmoGzXAixSrqM1tpolUzbg+cm+0Rr7oR6NnSvpOrKETZS3T3n/kesh3rCEzRemibOrjZBJnG8="
    - secure: "g/mU3dHk8TYTPKiLuhQwoCbN34Njh+zqFeBvMONF9QZ4xFPTkr6HjWtvyjDzKP5DWeC+1VTywYGYe7HNkU0U0gLrliXYejAv4/XW9WtwAgU4af6dw48i9h/EUTGN8Bopg9sxUMaQte5sjaxS7zFwldMRlc6ln7UFvtZDUUA/VI0="
    - secure: "N6RGJECfiayeo/MzJPDX55JxfVaTQ6iYEEkX1lFagyAI8OtQYKg3ziXajNVgL9KQuHxUY64rN3VA1eu0D44lbZumm4kk91NcdPheeJ0d7mEamg8nEy2msXYWm8/T0jo/lVEG3l4oqFyCgm/v11pfHhQ0sYxU/pX6GRRwxHzp4Uc="
    - secure: "TL8uXjWrdUN56qJu+NUk8Sj1sGVN+n7b9gyJU7Q2wsjcnR0hKQY+mygWqiGx3wL/BXY704snxWCiD6mCA1fWd7Xa2c3aEGmOI+csYM3MWgPzbI8cKMDs7jQ3fNs1e3qUZS6OXegBq1w1UQ5UwKbIpPebP6s5KTb93/pPAmNfQDI="
    - secure: "Mfk1WmnK76ApSlSzoG9wFHmv6V1WM47Qzis2XoPIeIrAQ6F0YjHikuon/EC6xaNXR9ZxNnmpBQIIZYvm7PpMyDpzA/VGFtwKw/RTpBO/bxS9cKlIarH3FosGjI9LcZ9ZF8oIONMzQHHzE4/Mg6JkGcyzsD5ZgDnAS3iz+2BuPjw="
    - secure: "g+kOgE/x3BVsEfq9dwRAhQNj9TmTChBqA02BEAX109WF437hq+wlAlLxfzfx0hJRbqLTne2h+WrRDo1/bKpmMAJ/eDqsLeYnyJfLUClfm4k/aioPv/+1LwlHWqVCt+KBWIcRlTx9sz3HKd4nu1Li4it4E5uZzD1APeDta90cVYc="
    - secure: "esOn69hQx25NS2TcPzj2JwEskKIzqJcFnPWWdcLgUAUTN4JVWcWjJQtcCVHq0dktrgsLvmkLUtoTjXgoML+X2tZQrpMyUIPxsmBKZEe08gmz4irEUjLWobLBZJLu7lWrGC05rPG6XQ57b9mjxXP8TAl1BB+3sRe8NNeQDt7i/uU="
    - secure: "Inp6s8VWqHAbs7n4megTxDYaO0083mj+AAAxVVEZL5/dNOAqxbtoYS3Aa/YgNa66M/tNLB5fRv83HUS/1WmVgZG42CJoDAOW7Gerb4unn4ezg7D50rKU0K0NKQYFZgRDRdp7TgC1E65lPrsjFIQ84cE0pmEaeUQXUzbHzplyA1g="
before_install:
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - gem install capistrano --no-ri --no-rdoc
  - eval "$(ssh-agent)"
  - ssh-add
before_script:
  - psql -c 'CREATE USER root with SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE uk_postcodes_test;' -U postgres
  - psql -d uk_postcodes_test -c 'CREATE SCHEMA postgis; CREATE EXTENSION postgis WITH SCHEMA postgis;' -U postgres
  - bundle exec rake db:migrate
after_success:
  - "[ \"$TRAVIS_BRANCH\" == \"master\" ] && bundle exec cap production deploy"